# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-07 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(verbose_name='商品id')),
                ('productimg', models.CharField(max_length=100, verbose_name='商品图片')),
                ('productname', models.CharField(max_length=100, verbose_name='商品短名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='售价')),
                ('marketprice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='市场售价')),
                ('storenums', models.IntegerField(verbose_name='库存')),
                ('productnum', models.IntegerField(verbose_name='销量')),
            ],
            options={
                'db_table': 'zol-goods',
            },
        ),
        migrations.DeleteModel(
            name='AxfNav',
        ),
        migrations.DeleteModel(
            name='AxfShop',
        ),
        migrations.DeleteModel(
            name='AxfWheel',
        ),
        migrations.DeleteModel(
            name='Mustbuy',
        ),
    ]
